version: "3"
services:
  web:
    build: .
    depends_on:
      - database
    env_file:
      - .env/development/database
      - .env/development/web
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/core_connection
  database:
    image: postgres:alpine
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
