version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - database
      - redis
    env_file:
      - .env/development/web
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/core_connection
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    command: bundle exec sidekiq
    depends_on:
      - database
      - redis
      - web
    env_file:
      - .env/development/web
    volumes:
      - .:/usr/src/core_connection
  database:
    image: postgres:alpine
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
volumes:
  db_data:
